version: '3'

services: 
    app:
        build: 
            context: api/.docker
        container_name: api_app
        entrypoint: api/.docker/entrypoint.sh
        volumes:
            - .:/usr/src/app
        tty: true
        ports: 
            - "3000:3000"
        environment: 
            - CHOKIDAR_USEPOLLING=true
        