version: '3'

services: 
    app:
        build: 
            context: api/.docker
        container_name: api_app
        volumes:
            - .:/usr/src/app
        tty: true
        ports: 
            - "3000:3000"
        