name: "CI"

on:
  push:
    branches:
      - untested-branch
  # pull_request:
  #   branches:
  #     - master

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
      - name: Install dependencies
        run: |
          cd api
          npm ci
          cd ..

  heroku_deploy:
    name: Heroku deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      env:
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
      run:
        docker build -t $HEROKU_APP .
    - name: Login into Heroku
      uses: actions/heroku@master
      with:
        args: container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Push to Heroku
      uses: actions/heroku@master
      with:
        args: container:push web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Trigger release in Heroku
      uses: actions/heroku@master
      with:
        args: container:release web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}

  integrations_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [build, heroku_deploy]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Newman
      run: | 
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    - name: Run integration tests
      run: npm run test:integration:heroku
    - name: Uploading testing content result to workspace
      uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: test-results