name: "Test-Build"

on:
  push:
    branches:
      - untested-branch
  # pull_request:
  #   branches:
  #     - master

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Create folder for results
        run: mkdir -p test-results

      - name: Run newman tests
        run: |
          newman run ./postman/Compound\ Interest.postman_collection.json -d ./tests/data-tests.json -r htmlextra --reporter-htmlextra-export test-results/htmlreport.html --reporter-htmlextra-darkTheme  > test-results/runreport1.html

      - name: Uploading testing content result to workspace
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: test-results