name: "CI"

on:
  push:
    branches:
      - untested-branch
  # pull_request:
  #   branches:
  #     - master

jobs:

  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker-compose stack
        run: docker-compose -f docker-compose.yaml up -d --build
      - name: Check running containers 
        run: docker-compose ps
      - name: Check containers logs
        run: docker logs api_app
  
  integrations_tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install Newman
      run: | 
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    - name: Create result folder
      run: mkdir -p test-results
    - name: Run integration tests
      run: docker exec -w /usr/src/app/api/ api_app npm run test:integration:local
    - name: Uploading testing content result to workspace
      uses: actions/upload-artifact@v2
      with:
        name: RunReports
        path: test-results

  heroku_deploy:
    name: Heroku deploy
    runs-on: ubuntu-latest
    needs: [build, integrations_tests]
    steps:
    - uses: actions/checkout@master
    - name: Login into Heroku
      uses: actions/heroku@master
      with:
        args: container:login
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Push to Heroku
      uses: actions/heroku@master
      with:
        args: container:push web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}
    - name: Trigger release in Heroku
      uses: actions/heroku@master
      with:
        args: container:release web
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP: ${{ secrets.HEROKU_APP }}

  stop_container:
    name: Stop Containers
    runs-on: ubuntu-latest
    needs: [heroku_deploy]
    steps:
      - uses: actions/checkout@master
      - name: Stop container
        run: docker-compose -f docker-compose.yaml down